spring.application.name=course-reg
spring.datasource.url=jdbc:postgresql://localhost:5432/coursereg_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081

# Development Spring Security Credentials
spring.security.user.name=admin
spring.security.user.password=admin123
